[package]
name = "geeks_git"
description = "Git crate for geeks productions."
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.14.3"
thiserror = "1.0.31"

[dev-dependencies]
geeks_git_testing = { path = "../geeks-git-testing" }
