[package]
name = "geeks_git"
description = "Git crate for geeks productions."
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.14.3"
thiserror = "1.0.31"

[dev-dependencies]
run_script = "0.9.0"
nanoid = "0.4.0"
